/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datadog_pej_springjni_SpringController */

#ifndef _Included_com_datadog_pej_springjni_SpringController
#define _Included_com_datadog_pej_springjni_SpringController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_datadog_pej_springjni_SpringController
 * Method:    displayHashMap
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_datadog_pej_springjni_SpringController_displayHashMap
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
