/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PassHashMap */

#ifndef _Included_PassHashMap
#define _Included_PassHashMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PassHashMap
 * Method:    displayHashMap
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_PassHashMap_displayHashMap
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
